' Option 1
@startuml
!pragma teoz true
autonumber


    participant "NAD Manager" as modu

    box "SOME/IP\n"
    participant "main thread" as mainTh
    participant "dispatcher thread" as dispTh
    end box

    participant "External Component" as ex
    'end box 

    
    modu ->> mainTh: send request


    mainTh -> mainTh: push message to handlers queue
    dispTh -> mainTh: get_next_handler()
    dispTh -> mainTh: invoke_handler()
    dispTh -> dispTh: create timer (100ms)
    dispTh -> dispTh: handle handler
    dispTh -> ex: send request

    alt if send_sections() return before timer expired
    
    ex --> dispTh: 
    dispTh -> dispTh: cancel timer
    else if timer expired and send_sections() is not return yet
    dispTh -> dispTh: create new dispatcher thread (< max_threads)
    dispTh -> dispTh: print blocking call
    ex --> dispTh:
    end

@enduml